name: Pull Request Opened

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Push
    uses: ./.github/workflows/cd-workflow.yml
    with:
      DOCKER_CONTEXT: .
      DOCKER_FILE: Dockerfile
      DOCKER_IMAGE_NAME: rbe5-images/rsbc-ride-console
      DOCKER_IMAGE_TAG: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
