name: Push - Check Build and Scan
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_build:
    name: Test the Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4    
      - name: Setup
        uses: docker/setup-buildx-action@v3
        with:
          install: true  
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false

  trivy-scan:
    uses: ./.github/workflows/trivy-scan-workflow.yml
    with:
      DOCKER_CONTEXT: .
      DOCKER_FILE: Dockerfile
      DOCKER_IMAGE_NAME: ride-console
    secrets: inherit
